server:
  port: 1032
  host: 0.0.0.0
  public: https://api.pylex.watch

api:
  endpoint: /api

logging:
  level: info
  file: logs/server.log

tmdb:
  api_key: 

vidsrc:
  api_key: dev
  remote: https://embed.su