server:
  port: 1032
  host: 0.0.0.0
  public: https://api.pylex.watch

api:
  endpoint: /api

logging:
  level: info
  file: logs/server.log

tmdb:
  api_key: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyMTRlNjFkZDk5NmU3NDUwMzI3YjE5ZmQxYzJhMTM0ZSIsIm5iZiI6MTczMjA1MTEzNS42NDk5OTk5LCJzdWIiOiI2NzNkMDBiZjUwNmRlZTdjMWEwNTcwN2YiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.NoaH92ZdfIE3ncFeLHpunLcxye3R7ReFWU7xBn1drk4

vidsrc:
  api_key: dev
  remote: https://embed.su